import type { Metadata } from "next";
import {Inter,Fraunces } from "next/font/google";
import { circularStd } from "./fonts";
import "./globals.css";
import { LayoutProvider } from "@/context/LayoutContext";
import Layout from "@/components/Layout";



const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <title>Infomerics Group : Home</title>
        <meta name="description" content="Infomerics Group" />
        <meta name="keywords" content="Infomerics Group" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        />
        <meta name="author" content="Infomerics Group" />

        <meta property="og:type" content="" />
        <meta property="og:title" content="" />
        <meta property="og:description" content="Infomerics Group" />
        <meta property="og:url" content="" />
        <meta property="og:image" content="" />

        <meta name="twitter:card" content="" />
        <meta name="twitter:site" content="" />
        <meta name="twitter:title" content="" />
        <meta name="twitter:description" content="Infomerics Group" />
        <meta name="twitter:image" content="" />

        <link
          type="image/x-icon"
          href="/ico/favicon.ico"
          rel="shortcut icon"
        />
        <link type="image/x-icon" href="/ico/favicon.ico" rel="icon" />

        <link rel="apple-touch-icon" href="/ico/android-chrome-192x192.png" />
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/ico/android-chrome-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/ico/android-chrome-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/ico/android-chrome-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/ico/android-chrome-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/ico/android-chrome-96x96.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/ico/android-chrome-144x144.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/ico/android-chrome-144x144.png"
        />

        {/* <link rel="stylesheet" href="/css/lib-min.css" /> */}
        {/* <link rel="stylesheet" href="/css/style.css" /> */}
      </head>
      <body
        className={`${circularStd.className} ${inter.variable} ${fraunces.variable} antialiased`}
      >
        <LayoutProvider>
          <Layout>{children}</Layout>
        </LayoutProvider>
      </body>
    </html>
  );
}
